In [4]:
from __future__ import print_function
import torch
from torch import nn

In [3]:
# construct a random maxtrix
x = torch.rand(5,3)
print(x)

tensor([[0.7692, 0.5052, 0.6036],
        [0.0760, 0.5789, 0.3462],
        [0.7348, 0.4145, 0.5981],
        [0.8881, 0.8629, 0.0936],
        [0.1753, 0.4764, 0.9188]])


In [7]:
rnn = nn.GRU(input_size= 10,hidden_size= 20,num_layers= 2) # 10 columns input, 
                # 20 number of features in the hidden states, which mean that GRU units has 20 columns, 10 rows
                # 2 layers means that 2 GRU stacking on the stop of each other, so 2 GRU units each 20 columns, 10 rows
input = torch.randn(5,3,10) # 5 samples, 3 rows, 10 columns
h0 = torch.randn(2,3,20)

In [8]:
print(input)
print('==================')
print(h0)

tensor([[[-0.6546, -0.7034, -0.0834, -0.4357,  0.4030,  0.0287,  0.1460,
          -0.5331, -1.1463,  0.7890],
         [-1.5141,  1.2489, -0.4471, -1.7335, -1.3891, -0.3373,  0.9839,
          -0.8935, -0.6172, -1.1233],
         [ 0.7861,  1.8301, -1.0875, -1.0763,  0.8734, -0.3574,  2.4262,
          -1.2154, -0.4193,  1.2761]],

        [[-0.9014, -0.2126,  0.8084, -0.0917, -0.2006,  0.6045, -0.6600,
          -0.2361, -0.4313, -1.9265],
         [ 0.0477,  0.6535,  0.7252,  0.0512, -1.6827, -0.1437, -0.9672,
           0.5336, -0.4918,  2.5779],
         [ 0.2624,  0.5041,  1.9770, -0.9947,  0.1077,  0.0459,  0.3251,
           1.0831,  0.6770,  0.2227]],

        [[ 0.4865,  0.3402,  0.2934, -0.2328, -1.2405, -1.2117,  0.6023,
          -0.4062, -0.3567, -1.2024],
         [ 1.2384, -1.5203,  0.8685, -0.2750, -0.0940,  0.9869, -0.7215,
           0.9894,  0.0644,  0.4780],
         [ 0.0813,  1.3853,  1.0293, -0.6814, -2.2849,  0.6050,  0.5958,
           0.3504, -0.7134,  0.0499

In [9]:
output, hn = rnn(input, h0)
# output: tensor containing the output features h_t from the last layer of GRU
# hn : tensor containing the hidden state for t = seq_len

In [10]:
print(output)

tensor([[[-1.2673e-01,  1.0052e-01, -1.8598e-01, -5.8282e-02, -9.9218e-02,
          -8.1107e-01,  8.5400e-01,  1.6805e-01, -4.2889e-01, -3.6627e-01,
           1.2527e+00,  2.2835e-02, -6.4946e-01, -1.2832e+00, -3.6643e-01,
          -5.2113e-01, -2.8520e-02, -7.7953e-01,  1.7450e-01, -4.7714e-01],
         [-8.5917e-02, -1.2557e-01, -5.3153e-01,  1.1123e+00,  1.9409e-01,
          -1.3703e+00, -1.2791e+00, -3.0865e-01, -9.9131e-01, -2.6021e-01,
           3.0152e-01, -3.9315e-01,  7.6967e-02,  5.0323e-01, -1.2669e+00,
           3.3649e-02, -1.0215e+00, -3.9383e-01, -4.7953e-01,  5.6187e-01],
         [-3.2587e-01,  5.9388e-01,  6.6342e-02, -2.4639e-01,  4.4723e-01,
           3.5413e-01, -5.6626e-01, -1.2087e-01,  6.5510e-01, -3.4411e-01,
           8.3223e-02,  6.5353e-01, -1.8013e-01, -4.2131e-01,  8.6981e-01,
           2.4083e-01,  1.1445e+00,  1.5593e-02, -8.2288e-01,  3.4800e-01]],

        [[-2.5153e-01,  4.4396e-02, -2.4417e-01,  6.7618e-02, -5.4877e-02,
          -5.2341e-0

In [11]:
print(hn)


tensor([[[-3.4458e-02,  3.2060e-01, -1.0255e-01, -9.8171e-02, -1.5633e-02,
          -1.2689e-04, -2.5318e-01, -2.2790e-01,  9.2613e-03,  3.7093e-01,
           1.4075e-01,  2.2326e-01,  2.1236e-01,  1.9505e-01,  1.4966e-01,
           1.3891e-01, -6.5645e-02, -2.2381e-01,  8.5626e-02,  5.1352e-02],
         [ 2.4264e-01,  4.0696e-01,  8.6578e-02, -1.4038e-01, -9.6659e-02,
          -2.1350e-01, -5.1851e-01,  4.0267e-01,  3.0450e-01, -6.0719e-02,
          -6.1318e-02, -2.3823e-02,  4.1023e-01,  2.3874e-01,  2.9701e-01,
           3.6603e-01,  9.6398e-02,  2.3080e-01,  4.0518e-01, -2.3730e-01],
         [ 3.2749e-01,  2.3202e-01, -4.9741e-01, -5.2107e-01, -4.5047e-02,
           9.8184e-02, -2.4374e-01,  2.4008e-01,  4.3663e-01, -5.8446e-02,
          -5.0776e-02, -1.2316e-01,  1.5456e-01, -9.1618e-02, -3.3326e-01,
           1.0361e-01,  5.3349e-01,  1.8425e-01,  5.5749e-02,  3.1708e-01]],

        [[-2.6804e-01,  2.2863e-01, -1.7156e-01, -5.1850e-02, -2.2173e-01,
          -2.8120e-0